In [1]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import  MultinomialNB
from sklearn import metrics
import pandas as pd

In [2]:
data=pd.read_csv("text_classification.csv",names=["message","label"])

In [3]:
data

                                 message label
0                   I love this sandwich   pos
1               this is an amazing place   pos
2     I feel very good about these beers   pos
3                   this is my best work   pos
4                   what an awesome view   pos
5          I do not like this restaurant   neg
6               I am tired of this stuff   neg
7                 I can't deal with this   neg
8                   he is my sworn enemy   neg
9                    my boss is horrible   neg
10              this is an awesome place   pos
11  I donot like the taste of this juice   neg
12                       I love to dance   pos
13     I am sick and tired of this place   neg
14                  what a great holiday   pos
15        that is a bad locality to stay   neg
16        we will have good fun tomorrow   pos
17      I went to my enemy's house today   neg

In [4]:
data['labelnum']=data['label'].map({"pos":1,"neg":0})

In [5]:
data

                                 message label  labelnum
0                   I love this sandwich   pos         1
1               this is an amazing place   pos         1
2     I feel very good about these beers   pos         1
3                   this is my best work   pos         1
4                   what an awesome view   pos         1
5          I do not like this restaurant   neg         0
6               I am tired of this stuff   neg         0
7                 I can't deal with this   neg         0
8                   he is my sworn enemy   neg         0
9                    my boss is horrible   neg         0
10              this is an awesome place   pos         1
11  I donot like the taste of this juice   neg         0
12                       I love to dance   pos         1
13     I am sick and tired of this place   neg         0
14                  what a great holiday   pos         1
15        that is a bad locality to stay   neg         0
16        we will have good fun tomorrow   pos         1
17      I went to my enemy's house today   neg         0

In [6]:
inp_data=data['message']
output=data['labelnum']

In [7]:
x_train,x_test,y_train,y_test=train_test_split(inp_data,output,test_size=0.3,random_state=5)
cv=CountVectorizer()

In [8]:
x_train_1=cv.fit_transform(x_train)
x_test_1=cv.transform(x_test)

In [9]:
df=pd.DataFrame(x_train_1.toarray(),columns=cv.get_feature_names_out())

In [10]:
df

,am,an,and,awesome,bad,best,boss,can,dance,deal,...,this,tired,to,tomorrow,view,we,what,will,with,work
0,0,0,0,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,1,0,1,...,1,0,0,0,0,0,0,0,1,0
2,0,1,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,1,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,1,0,1,0,0
7,1,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
8,1,0,1,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
9,0,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
11,0,0,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1

In [11]:
clf=MultinomialNB()

In [12]:
clf=clf.fit(x_train_1,y_train)

In [13]:
pred=clf.predict(x_test_1)

In [15]:
print("accuracy is :",metrics.accuracy_score(y_test,pred))

accuracy is : 0.8333333333333334

In [16]:
print("confusion matrix :",metrics.confusion_matrix(y_test,pred))

confusion matrix : [[3 0]
 [1 2]]

In [17]:
print("precesion is :",metrics.precision_score(y_test,pred))

precesion is : 1.0

In [20]:
print("recall is :",metrics.recall_score(y_test,pred))

recall is : 0.6666666666666666